### PR TITLE
Changed images for fixing typo

### PR DESCRIPTION
**Pull request by dmainardi**
Image about "using a password alias in JDBC Connection Pool" contained a typo:
${alias=example-alias-name}
should be
${ALIAS=example-alias-name}

I took the two screenshots and uploaded the images (without and with using a password alias)

### CODE REVIEW

**Comment by mikecroft** [comment]
Looks great, thanks! We'll just wait for confirmation that the CLA has been received and then we can get this merged 👍

**Comment by mikecroft** [comment]
Removed the CLA label for now because it's not been confirmed and added to the internal list yet

**Comment by dmainardi** [comment]
I sent the CLA on 11.21 CET. My e-mail address is ingmainardi at live dot com
Attachment is quite big (more than 1,5 MB), hope you received it.

**Comment by mikecroft** [comment]
I'm sure we will! I've told my colleagues so they will update our internal documentation when they can, then we'll get this merged :smiley:

**Comment by smillidge** [comment]
Yeah we have the CLA signed. @mikecroft usually we have a green CLA label when we have the CLA and a yellow Awiting CLA label it confused me ;-)

**Pull request merged**
