### PR TITLE
PAYARA-4142: Prepare TCK results documentation section

### PR DESCRIPTION
**Pull request by pdudits**
image

This adds section for publishing TCK test results.
Actual test outputs are commented out at this point, we can compare and uncomment them as CI jobs will complete.

### CODE REVIEW

**Comment by jbee** [comment]
Wouldn't this better be shown in a table? Current format seems unnecessary lengthy and full of boilerplate.

**Comment by MattGill98** [comment]
I agree, I also think there should be a clear sign of what it means when there is no sign of the current result

**Comment by pdudits** [comment]
> 
> 
> Wouldn't this better be shown in a table? Current format seems unnecessary lengthy and full of boilerplate.

This appears to be the form in which TCK results are presented (see [Glassfish](https://eclipse-ee4j.github.io/glassfish/certifications/jakarta-full-profile/8.0/TCK-Results), [Wildfly](https://github.com/wildfly/certifications/blob/EE8/WildFly_17.0.1.Final/jakarta-full-profile.adoc) or [Openliberty](https://openliberty.io/certifications/jakartaee/platform/8/TCKResults.html)). I just highlight the suite names between test outputs.



> 
> 
> 
> 
> Wouldn't this better be shown in a table? Current format seems unnecessary lengthy and full of boilerplate.

This appears to be the form in which TCK results are presented (see [Glassfish](https://eclipse-ee4j.github.io/glassfish/certifications/jakarta-full-profile/8.0/TCK-Results), [Wildfly](https://github.com/wildfly/certifications/blob/EE8/WildFly_17.0.1.Final/jakarta-full-profile.adoc) or [Openliberty](https://openliberty.io/certifications/jakartaee/platform/8/TCKResults.html)). I just highlight the suite names between test outputs.

> I agree, I also think there should be a clear sign of what it means when there is no sign of the current result

Do you mean improving the wording of the current one (screenshot doesn't include it, sorry for misledading)? "NOTE: This page reflects work in progress. Test results will be added as they pass CI build of final release candidate of the version."

**Comment by MattGill98** [comment]
I think that comment at the top clarifies it nicely!

**Comment by jbee** [comment]
> This appears to be the form in which TCK results are presented

:face_with_head_bandage:

**Pull request merged**
