### PR TITLE
Splitting of Payara Micro documentation into multiple files (PYSVC-74)

### PR DESCRIPTION
**Pull request by OndrejM**
Internal task PYSVC-74
Preview of the gitbook with these changes is available here: https://ondrejm.gitbooks.io/payara-server-documentation-fork/content/v/next_PYSVC-74

### CODE REVIEW

**Comment by OndrejM** [comment]
Preview of the gitbook with these changes is available here: https://ondrejm.gitbooks.io/payara-server-documentation-fork/content/v/next_PYSVC-74

**Comment by mikecroft** [comment]
Hi Ondrej,

Could you add the extra section from Susan's pull request:
https://github.com/payara/Payara-Server-Documentation/pull/52/files

I don't think you need to do this before the 163 release, we can patch it in afterwards, so no rush. It might be good to wait, actually, since there might be more stuff to go in there later before release.

I think the actual conflicts that GitHub is complaining about are to do with your other change to add an appendix for the release notes, though. Other than that the change is good! Shows how needed it was too, I hadn't realised how big that one file had become.

**Comment by OndrejM** [comment]
I synchronized this PR with the *next* branch. Susan's PR is already added, see here in this preview: https://ondrejm.gitbooks.io/payara-server-documentation-fork/content/v/next_PYSVC-74/documentation/payara-micro/logging-to-file.html

It hould be safe to merge this PR now.

**Comment by smillidge** [comment]
looks awesome

**Comment by smillidge** [comment]
could we merge this into master at this point to make life easier adding additional payara micro docs relevant to 163?

**Comment by OndrejM** [comment]
I'll merge it into 163 too.

**Comment by OndrejM** [comment]
Merged into 163 by PR #71.
Don't forget to let us now soon after you update the 163 docs, so that we (support team) may merge it also to "next" branch. Or merge to "next" branch by yourselves.

**Pull request merged**
