### PR TITLE
Added custom JACC Provider registration instruccions

### PR DESCRIPTION
**Pull request by ggam**
Simple instructions but hopefully enough to help users get some insight.

Based on the research from @arjantijms.

### CODE REVIEW

**Comment by mikecroft** [comment]
This is great, thanks! We need a CLA as I posted in the issue you created, but while that is happening, could you make this pull request into the `next` branch please? The plan is that all future changes go in there and that `master` is kept at the level of the most recent release (`162`).

We did look at merging in changes to `master` when they were applicable to current and previous versions, but it made the release process very messy with conflicting changes in `next` and `master`.

Thanks!

**Comment by ggam** [comment]
Hi! Sorry for the late response. I'll change the branch. The CLA has to be sent by fax or postal coded or is there any other way? Thanks!

**Comment by mikecroft** [comment]
A scan works too! I've used CamScanner in the past which means you can take a photo with your smartphone and it will be converted to PDF and you can email it from within the app.
https://www.camscanner.com/

**Comment by smillidge** [comment]
I can confirm we have the CLA

**Comment by mikecroft** [comment]
Manually merged into `next` branch

**Comment by ggam** [comment]
Excuse me, I see I created my other pull request to the 162 branch...
Thanks for fixing it!

**Comment by mikecroft** [comment]
No problem! Thanks for taking the time to document the feature :+1:

**Pull request closed without merging**
